"use client";

import { useState } from "react";
import { LazyImage } from "./components/RandomFox";
import type { MouseEventHandler } from "react";
import { random } from "lodash";

const randomnumber = () => random( 1, 123 );
const generateId = () => Math.random().toString(36).substr(2,9);


export default function Home() {

  const [images, setImages] = useState<ImageItem[]>( [] );

  const addNewFox:MouseEventHandler<HTMLButtonElement> = (event) => {

    event.preventDefault();

    //window.plausible( "Stoe" );

    const newImage: ImageItem = { 
      id: generateId(), 
      url: `https://randomfox.ca/images/${randomnumber()}.jpg` 
    };

    setImages([
      ...images,
      newImage
    ]);
  };

  return (
    <div>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </head>

      <main>
        <h1 className="text-3xl font-bold underline">Hey Platzi 😎!</h1>

        <button onClick={addNewFox}>Add Fox</button>

        { images.map( ( {id, url}, index ) =>(  
          <div key={id} className="p-4">
            <LazyImage 
              src={url} 
              onClick={() => { console.log( 'Mi click' ); }} 
              className="rounded bg-gray-300" 
              width={320} 
              height="auto"
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }} 
            />
          </div>
        ) ) }

        

      </main>

      <footer></footer>
    </div>
  );
}
